[package]
name = "phaedra-uds"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/PaleRoses/phaedra"
description = "Portable unix domain sockets"
license = "MIT"
documentation = "https://docs.rs/phaedra-uds"

[dependencies]
async-io.workspace = true
uds_windows.workspace = true
