[package]
name = "umask"
version = "0.1.0"
authors = ["PaleRoses"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static.workspace = true
libc.workspace = true
