[package]
name = "tabout"
version = "0.3.0"
authors = ["PaleRoses"]
edition = "2018"
repository = "https://github.com/PaleRoses/phaedra"
description = "Tabulate output for CLI programs"
license = "MIT"
documentation = "https://docs.rs/tabout"

[dependencies]
termwiz.workspace = true
