[package]
name = "rangeset"
version = "0.1.0"
authors = ["PaleRoses"]
edition = "2018"
publish = false

[dependencies]
num.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "rangeset"
harness = false

